CREATE column TABLE EOC.MD_O_BusinessPartner (
    BusinessPartner             NVARCHAR (10)  NOT NULL,
    DeleteFlag                  SMALLINT       NOT NULL,
    CreateDate                  DATETIME       NOT NULL,
    CreateUser                  NVARCHAR (32)  NOT NULL,
    ModifyDate                  DATETIME       NOT NULL,
    ModifyUser                  NVARCHAR (32)  NOT NULL,
    DataSourceRef               NVARCHAR (32)  NOT NULL,
    BusinessPartnerDesc         NVARCHAR (163) NULL,
    SearchTerm1                 NVARCHAR (20)  NULL,
    SearchTerm2                 NVARCHAR (20)  NULL,
    PartnerType                 NVARCHAR (4)   NULL,
    AuthorizationGroup          NVARCHAR (4)   NULL,
    Language                    NVARCHAR (1)   NULL,
    LanguageISO                 NVARCHAR (2)   NULL,
    DataOrigin                  NVARCHAR (4)   NULL,
    ToBeArchived                NVARCHAR (1)   NULL,
    CentralBlock                NVARCHAR (1)   NULL,
    FormOfAddress               NVARCHAR (4)   NULL,
    ContactPermission           NVARCHAR (1)   NULL,
    ExternalPartner             NVARCHAR (20)  NULL,
    LetterSalutation            NVARCHAR (50)  NULL,
    NotReleased                 NVARCHAR (1)   NULL,
    CommunicationType           NVARCHAR (3)   NULL,
    PrintMode                   NVARCHAR (1)   NULL,
    LegalForm                   NVARCHAR (2)   NULL,
    IndustrySector              NVARCHAR (10)  NULL,
    FoundationDate              DATETIME       NULL,
    LiquidationDate             DATETIME       NULL,
    InternationalLocationNumber NVARCHAR (13)  NULL,
    LegalEntity                 NVARCHAR (2)   NULL,
    DomicileState               NVARCHAR (3)   NULL,
    Area                        NVARCHAR (24)  NULL,
    IsFETExempt                 NVARCHAR (1)   NULL,
    BusinessPartnerStatus       NVARCHAR (5)   NULL,
    NaturalPerson               NVARCHAR (1)   NULL,
    ImmediateParent             NVARCHAR (10)  NULL,
    UltimateParent              NVARCHAR (10)  NULL,
    SAPCreateUser               NVARCHAR (12)  NULL,
    SAPModifyUser               NVARCHAR (12)  NULL
);


