CREATE column TABLE eoc.qv_FinancialsOriginalIntl
(
	CreateDate datetime NOT NULL,	
	ModifyDate datetime NOT NULL,	
	AccountSK int NOT NULL,
	AccountPostingNumber nvarchar(60) NOT NULL,
	CompanySK smallint NOT NULL,
	CedentSK int NOT NULL,
	TreatySK int NOT NULL,
	TreatyPeriodSK int NOT NULL,
	TreatySectionSK int NOT NULL,
	TreatyInvolvementSK int NOT NULL,
	AccountingUnitSK int NOT NULL,
	LineOfBusinessSK int NOT NULL,
	LossSK int NOT NULL,
	ActivitySK int NOT NULL,
	ClaimObjectSK bigint NOT NULL,
	EstimateSK smallint NOT NULL,
	EntryCodeSK int NOT NULL,
	PostingRecordSK bigint NOT NULL,
	UnderwritingAreaSK int NOT NULL,
	
	TreatyHistorySK int NOT NULL,
	TreatySectionHistorySK int NOT NULL,
	TreatyInvolvementHistorySK int NULL,
	BrokerSK int NOT NULL,
	IBNRReserveCellSK int NOT NULL,
	MCOBSK int NOT NULL,
	LineOfBusinessCode nvarchar(24) NOT NULL,			
	AccountStatusCode nvarchar(3) NOT NULL,
	AccountPeriodEndDate date NOT NULL,
	UnderwritingDate date NOT NULL,	
	OccurrenceDate date NOT NULL,	
	FIPostingDate date NOT NULL,
	FinancialPeriod int NOT NULL,
	AccountingPeriod int NULL,
	AccountingYear smallint NOT NULL,
	UnderwritingYear smallint NOT NULL,
	GenReUnderwritingYear smallint NOT NULL,	
	OccurrenceYear smallint NOT NULL,
	OriginalCurrencySK smallint NOT NULL,		
	OriginalCurrency nvarchar(5) NOT NULL,	
	OriginalAmount decimal(24, 4) NOT NULL
	)