CREATE column TABLE eoc.EW_F_DRW_FSCD (
    FSCDSK                BIGINT          NOT NULL,
    DeleteFlag            SMALLINT        NOT NULL,
    CreateDate            DATETIME        NOT NULL,
    CreateUser            NVARCHAR (32)   NOT NULL,
    ModifyDate            DATETIME        NOT NULL,
    ModifyUser            NVARCHAR (32)   NOT NULL,
    DataSource            NVARCHAR (32)   NOT NULL,
    DataSourceRef         NVARCHAR (32)   NOT NULL,
    AccountSK             INT             NOT NULL,
    CompanySK             SMALLINT        NOT NULL,
    CedentSK              INT             NOT NULL,
    TreatySK              INT             NOT NULL,
    TreatyInvolvementSK   INT             NOT NULL,
    LossSK                INT             NOT NULL,
    ActivitySK            INT             NOT NULL,
    FinancialReportingSK  INT             NOT NULL,
    FSCDItemSK            INT             NOT NULL,
    EstimateSK            SMALLINT        NOT NULL,
    EntryCodeSK           INT             NOT NULL,
    UnderwritingAreaSK    INT             NOT NULL,
    LedgerGroupSK         INT             NOT NULL,
    TradingPartnerSK      INT             NOT NULL,
    BrokerSK              INT             NOT NULL,
    IBNRReserveCellSK     INT             NOT NULL,
    GLAccountSK           INT             NOT NULL,
    MCOBSK                INT             NOT NULL,
    OriginalCurrencySK    SMALLINT        NOT NULL,
    AccountingCurrencySK  SMALLINT        NOT NULL,
    TransactionCurrencySK SMALLINT        NOT NULL,
    CompanyCurrencySK     SMALLINT        NOT NULL,
    HomeCurrencySK        SMALLINT        NOT NULL,
    GroupCurrencySK       SMALLINT        NOT NULL,
    CashFlow              NVARCHAR (10)   NOT NULL,
    DocumentType          NVARCHAR (2)    NOT NULL,
    PaymentItem           INT             NOT NULL,
    AccountStatusCode     NVARCHAR (3)    NOT NULL,
    AccountPeriodEndDate  DATE            NOT NULL,
    UnderwritingDate      DATE            NOT NULL,
    OccurrenceDate        DATE            NOT NULL,
    ClearingDate          DATE            NOT NULL,
    DeferralDate          DATE            NOT NULL,
    NetDueDate            DATE            NOT NULL,
    FIPostingDate         DATE            NOT NULL,
    FinancialPeriod       INT             NOT NULL,
    AccountingPeriod      INT             NULL,
    AccountingYear        SMALLINT        NOT NULL,
    UnderwritingYear      SMALLINT        NOT NULL,
    GenReUnderwritingYear SMALLINT        NULL,
    OccurrenceYear        SMALLINT        NOT NULL,
    OriginalCurrency      NVARCHAR (5)    NOT NULL,
    AccountingCurrency    NVARCHAR (5)    NOT NULL,
    TransactionCurrency   NVARCHAR (5)    NOT NULL,
    CompanyCurrency       NVARCHAR (5)    NOT NULL,
    HomeCurrency          NVARCHAR (5)    NOT NULL,
    GroupCurrency         NVARCHAR (5)    NOT NULL,
    OriginalAmount        DECIMAL (24, 4) NOT NULL,
    AccountingAmount      DECIMAL (24, 4) NOT NULL,
    TransactionAmount     DECIMAL (24, 4) NOT NULL,
    CompanyAmount         DECIMAL (24, 4) NOT NULL,
    HomeAmount            DECIMAL (24, 4) NOT NULL,
    GroupAmount           DECIMAL (24, 4) NOT NULL
);
