CREATE column TABLE EOC.EO_O_GTFEPeriod (
    PeriodGuid            VARCHAR (22),
    DeleteFlag            SMALLINT      NOT NULL,
    CreateDate            DATETIME      NOT NULL,
    CreateUser            NVARCHAR (32) NOT NULL,
    ModifyDate            DATETIME      NOT NULL,
    ModifyUser            NVARCHAR (32) NOT NULL,
    DataSourceRef         NVARCHAR (32) NOT NULL,
    TreatyGuid            VARCHAR (22),
    TreatyPeriodStartDate DATETIME      NOT NULL,
    TreatyPeriodEndDate   DATETIME      NOT NULL,
    ProcessStatus         NVARCHAR (3)  NULL,
    SAPChangeDate         DATETIME      NULL,
    ReferralCategory      CHAR (1)      NULL,
    FSRIPeriodStatus      NVARCHAR (3)  NULL,
    BusinessStatus        NVARCHAR (2)  NULL,
    OutcomeStatus         NVARCHAR (2)  NULL,
    UnderwritingStatus    NVARCHAR (2)  NULL,
    GuidelineStatus       NVARCHAR (2)  NULL,
    GuidelineGuid         NVARCHAR (22) NULL,
    UnderwritingGuid      NVARCHAR (22) NULL,
    MarketingGuid         NVARCHAR (22) NULL,
    AnniversaryDate       DATETIME      NULL,
    ContractRequestDate   DATETIME      NULL
);