CREATE column TABLE "EOC"."EO_O_GTFESection" (
    SectionGuid           VARCHAR (22)  NOT NULL,
    DeleteFlag            SMALLINT      NOT NULL,
    CreateDate            DATETIME      NOT NULL,
    CreateUser            NVARCHAR (32) NOT NULL,
    ModifyDate            DATETIME      NOT NULL,
    ModifyUser            NVARCHAR (32) NOT NULL,
    DataSourceRef         NVARCHAR (32) NOT NULL,
    TreatyGuid            VARCHAR (22)  NOT NULL,
    Section               NVARCHAR (4)  NULL,
    TreatyType            NVARCHAR (3)  NULL,
    SAPChangeDate         DATETIME      NULL,
    SectionDesc           NVARCHAR (40) NULL,
    Layer                 NVARCHAR (2)  NULL,
    MainCOB               NVARCHAR (24) NULL,
    CutOffRunOff          CHAR (1)      NULL,
    BusinessType          NVARCHAR (3)  NULL,
    UnderwritingArea      NVARCHAR (24) NULL,
    RunOffPeriod          NVARCHAR (4)  NULL,
    PremiumAccountingMode NVARCHAR (2)  NULL,
    LossAccountingMode    NVARCHAR (2)  NULL,
    Sunset                DECIMAL (10)  NULL,
    TimeUnitSunset        NVARCHAR (4)  NULL,
    ArtificialIndicator   CHAR (1)      NULL
);