CREATE Column TABLE eoc.EW_O_Accountc (
    AccountSK              bigINT           NOT NULL,
    DeleteFlag             SMALLINT      NOT NULL,
    CreateDate             DATETIME      NOT NULL,
    CreateUser             NVARCHAR (32) NOT NULL,
    ModifyDate             DATETIME      NOT NULL,
    ModifyUser             NVARCHAR (32) NOT NULL,
    DataSourceRef          NVARCHAR (32) NOT NULL,
    ActivitySK             INT           NULL,
    Account                NVARCHAR (20) NULL,
    AccountDesc            NVARCHAR (80) NULL,
    AccountStatus          NVARCHAR (20) NULL,
    AccountStatusCode      NVARCHAR (3)  NULL,
    AccountStatusDesc      NVARCHAR (40) NULL,
    AccountPeriodStartDate DATE          NULL,
    AccountPeriodEndDate   DATE          NULL,
    AccountingYear         SMALLINT      NULL,
    AccountReleaseDate     DATE          NULL,
    AccountCedent          NVARCHAR (10) NULL,
    AccountCedentDesc      NVARCHAR (40) NULL,
    AccountReceiptDate     DATE          NULL,
    AccountDueDate         DATE          NULL,
    AccountCreateDate      DATE          NULL,
    LogicalSystem          NVARCHAR (2)  NULL,
    PartnersInvolved       NVARCHAR (10) NULL,
    PartnersInvolvedDesc   NVARCHAR (40) NULL,
    ExternalPartner        NVARCHAR (10) NULL,
    ExternalPartnerDesc    NVARCHAR (40) NULL,
    AccountFunction        NVARCHAR (3)  NULL,
    AccountOrigin          NVARCHAR (3)  NULL,
    AccountFunctionDesc    NVARCHAR (80) NULL,
    AccountOriginDesc      NVARCHAR (40) NULL,
    ReleaseDate            DATE          NULL,
    OriginalCedent         NVARCHAR (10) NULL,
    OriginalCedentDesc     NVARCHAR (40) NULL,
    AccountCreateTime      TIMESTAMP     NULL,
    AccountReleaseTime     TIMESTAMP      NULL,
    AccountingPeriod       NVARCHAR (5)  NULL,
    AccountingPeriodDesc   NVARCHAR (40) NULL,
    Treaty                 NVARCHAR (20) NULL,
    Section                NVARCHAR (4)  NULL,
    TransactionType        NVARCHAR (4)  NULL,
    BusinessType           NVARCHAR (50) NULL,
    AvsEAllocationPeriod   NVARCHAR (50) NULL,
    AccountOverdueBand     NVARCHAR (50) NULL,
    CAPLogComplete         CHAR (1)      NULL,
    ProvisionalEntry       CHAR (1)      NULL,
    AccountingFrequency    NVARCHAR (3)  NULL
);